/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-10-27 12:11:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1635334967603L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1635333930441L));
    _jspx_dependants.put("/WEB-INF/views/common/aside.jsp", Long.valueOf(1635332794232L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	String str = "Hello world";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<script src=\"/web/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("const name = \"홍길동\";\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("div, section,header,aside,footer {padding:10px;}\r\n");
      out.write("div#container	{ background-color:#F0F0F0; width:960px; margin:0 auto;}\r\n");
      out.write("header				{background-color:#908886; height:100px; }\r\n");
      out.write("nav					{float:right; transform: translateY(-10px); }\r\n");
      out.write("nav ul {display: flex;}\r\n");
      out.write("nav ul li			{list-style:none; }\r\n");
      out.write("nav ul li a			{text-decoration:none;color:black; padding:0 10px;}\r\n");
      out.write("nav ul li:not(:last-of-type)::after  {content: \"|\"}	\r\n");
      out.write("nav ul li a:hover	{color:white;}\r\n");
      out.write("section#content		{background-color:#F5F5F5; float:left; width:640px; min-height:500px; }\r\n");
      out.write("aside				{background-color:#DCDAD9; float:right; width:280px; min-height:500px; }\r\n");
      out.write("footer { background-color:#555555; clear:both;  text-align:center; padding-bottom: 30px; } \r\n");
      out.write("footer h3 { text-align: left; }\r\n");
      out.write("</style>\r\n");
      out.write("<title>HTML5 레이아웃</title>\r\n");
      out.write("</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		<div id=\"container\">\r\n");
      out.write("			<header>\r\n");
      out.write("				<h2>Header</h2>\r\n");
      out.write("				<nav>\r\n");
      out.write("					<ul class=\"navi\">\r\n");
      out.write("						<li><a href=\"/web/main.jsp\">Home</a></li>\r\n");
      out.write("						<li><a href=\"/web/html5.jsp\">HTML5</a></li>\r\n");
      out.write("						<li><a href=\"/web/css3.jsp\">CSS3</a></li>\r\n");
      out.write("						<li><a href=\"/web/js.jsp\">Javascript</a></li>\r\n");
      out.write("						<li><a href=\"/web/jquery.jsp\">JQuery</a></li>\r\n");
      out.write("						<li><a href=\"/web/mobile.jsp\">Mobile</a></li>\r\n");
      out.write("						<li><a href=\"/web/profile.jsp\">Profile</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</header>");
      out.write("\r\n");
      out.write("			<section id=\"content\">\r\n");
      out.write("				<h3>Home</h3>\r\n");
      out.write("				<p>");
      out.print( str );
      out.write("</p>\r\n");
      out.write("			</section>\r\n");
      out.write("\r\n");
      out.write("			<aside>\r\n");
      out.write("				<h4>Aside</h4>\r\n");
      out.write("			</aside>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("			<footer>\r\n");
      out.write("				<h3>Footer</h3>\r\n");
      out.write("				<p>&lt;Copyright 2017. <strong>KH정보교육원</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("			</footer>\r\n");
      out.write("		</div>\r\n");
      out.write("		<script>\r\n");
      out.write("		$(\"*\").css(\"color\", \"red\");\r\n");
      out.write("		</script>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
