/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2022-01-14 13:53:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Welcome Area Start -->\r\n");
      out.write("    <section class=\"welcome-area\">\r\n");
      out.write("        <div class=\"welcome-slides owl-carousel\">\r\n");
      out.write("            <!-- Single Welcome Slide -->\r\n");
      out.write("            <div class=\"single-welcome-slide bg-img bg-overlay\" style=\"background-image: url(roberto/img/bg-img/16.jpg);\" data-img-url=\"roberto/img/bg-img/16.jpg\">\r\n");
      out.write("                <!-- Welcome Content -->\r\n");
      out.write("                <div class=\"welcome-content h-100\">\r\n");
      out.write("                    <div class=\"container h-100\">\r\n");
      out.write("                        <div class=\"row h-100 align-items-center\">\r\n");
      out.write("                            <!-- Welcome Text -->\r\n");
      out.write("                            <div class=\"col-12\">\r\n");
      out.write("                                <div class=\"welcome-text text-center\">\r\n");
      out.write("                                    <h6 data-animation=\"fadeInLeft\" data-delay=\"200ms\">Rental &amp; Resale</h6>\r\n");
      out.write("                                    <h2 data-animation=\"fadeInLeft\" data-delay=\"500ms\">Welcome To Bookit</h2>\r\n");
      out.write("                                    <a href=\"#\" class=\"btn roberto-btn btn-2\" data-animation=\"fadeInLeft\" data-delay=\"800ms\">Discover Now</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Single Welcome Slide -->\r\n");
      out.write("            <div class=\"single-welcome-slide bg-img bg-overlay\" style=\"background-image: url(roberto/img/bg-img/17.jpg);\" data-img-url=\"roberto/img/bg-img/17.jpg\">\r\n");
      out.write("                <!-- Welcome Content -->\r\n");
      out.write("                <div class=\"welcome-content h-100\">\r\n");
      out.write("                    <div class=\"container h-100\">\r\n");
      out.write("                        <div class=\"row h-100 align-items-center\">\r\n");
      out.write("                            <!-- Welcome Text -->\r\n");
      out.write("                            <div class=\"col-12\">\r\n");
      out.write("                                <div class=\"welcome-text text-center\">\r\n");
      out.write("                                    <h6 data-animation=\"fadeInUp\" data-delay=\"200ms\">Rental &amp; Resale</h6>\r\n");
      out.write("                                    <h2 data-animation=\"fadeInUp\" data-delay=\"500ms\">Welcome To Bookit</h2>\r\n");
      out.write("                                    <a href=\"#\" class=\"btn roberto-btn btn-2\" data-animation=\"fadeInUp\" data-delay=\"800ms\">Discover Now</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Single Welcome Slide -->\r\n");
      out.write("            <div class=\"single-welcome-slide bg-img bg-overlay\" style=\"background-image: url(img/bg-img/18.jpg);\" data-img-url=\"img/bg-img/18.jpg\">\r\n");
      out.write("                <!-- Welcome Content -->\r\n");
      out.write("                <div class=\"welcome-content h-100\">\r\n");
      out.write("                    <div class=\"container h-100\">\r\n");
      out.write("                        <div class=\"row h-100 align-items-center\">\r\n");
      out.write("                            <!-- Welcome Text -->\r\n");
      out.write("                            <div class=\"col-12\">\r\n");
      out.write("                                <div class=\"welcome-text text-center\">\r\n");
      out.write("                                    <h6 data-animation=\"fadeInDown\" data-delay=\"200ms\">Rental &amp; Resale</h6>\r\n");
      out.write("                                    <h2 data-animation=\"fadeInDown\" data-delay=\"500ms\">Welcome To Bookit</h2>\r\n");
      out.write("                                    <a href=\"#\" class=\"btn roberto-btn btn-2\" data-animation=\"fadeInDown\" data-delay=\"800ms\">Discover Now</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Welcome Area End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- About Us Area Start -->\r\n");
      out.write("    <section class=\"roberto-about-area section-padding-100-0\">\r\n");
      out.write("        <!-- Hotel Search Form Area -->\r\n");
      out.write("        <div class=\"book-search-form-area\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"book-search-form\">\r\n");
      out.write("                    <form action=\"#\" method=\"post\">\r\n");
      out.write("                        <div class=\"row justify-content-between align-items-end\">\r\n");
      out.write("                            <div class=\"col-6 col-md-2 col-lg-3\">\r\n");
      out.write("                                <label for=\"checkIn\">대여 시작일</label>\r\n");
      out.write("                                <input type=\"date\" class=\"form-control\" id=\"checkIn\" name=\"checkin-date\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-6 col-md-2 col-lg-3\">\r\n");
      out.write("                                <label for=\"checkOut\">대여 종료일</label>\r\n");
      out.write("                                <input type=\"date\" class=\"form-control\" id=\"checkOut\" name=\"checkout-date\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-6 col-md-2 col-lg-3\">\r\n");
      out.write("                            	<label for=\"bookTitle\">책 제목</label>\r\n");
      out.write("                            	<input type=\"text\" class=\"form-control\" id=\"bookTitle\" placeholder=\"책 제목을 입력하세요 ...\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- <div class=\"col-4 col-md-1\">\r\n");
      out.write("                                <label for=\"room\">Room</label>\r\n");
      out.write("                                <select name=\"room\" id=\"room\" class=\"form-control\">\r\n");
      out.write("                                    <option value=\"01\">01</option>\r\n");
      out.write("                                    <option value=\"02\">02</option>\r\n");
      out.write("                                    <option value=\"03\">03</option>\r\n");
      out.write("                                    <option value=\"04\">04</option>\r\n");
      out.write("                                    <option value=\"05\">05</option>\r\n");
      out.write("                                    <option value=\"06\">06</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-4 col-md-1\">\r\n");
      out.write("                                <label for=\"adults\">Adult</label>\r\n");
      out.write("                                <select name=\"adults\" id=\"adults\" class=\"form-control\">\r\n");
      out.write("                                    <option value=\"01\">01</option>\r\n");
      out.write("                                    <option value=\"02\">02</option>\r\n");
      out.write("                                    <option value=\"03\">03</option>\r\n");
      out.write("                                    <option value=\"04\">04</option>\r\n");
      out.write("                                    <option value=\"05\">05</option>\r\n");
      out.write("                                    <option value=\"06\">06</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-4 col-md-2 col-lg-1\">\r\n");
      out.write("                                <label for=\"children\">Children</label>\r\n");
      out.write("                                <select name=\"children\" id=\"children\" class=\"form-control\">\r\n");
      out.write("                                    <option value=\"01\">01</option>\r\n");
      out.write("                                    <option value=\"02\">02</option>\r\n");
      out.write("                                    <option value=\"03\">03</option>\r\n");
      out.write("                                    <option value=\"04\">04</option>\r\n");
      out.write("                                    <option value=\"05\">05</option>\r\n");
      out.write("                                    <option value=\"06\">06</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div> -->\r\n");
      out.write("                            <div class=\"col-12 col-md-3\">\r\n");
      out.write("                                <button type=\"submit\" class=\"form-control btn roberto-btn w-100\">Check Availability</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container mt-100\">\r\n");
      out.write("            <div class=\"row align-items-center\">\r\n");
      out.write("                <div class=\"col-12 col-lg-6\">\r\n");
      out.write("                    <!-- Section Heading -->\r\n");
      out.write("                    <div class=\"section-heading wow fadeInUp\" data-wow-delay=\"100ms\">\r\n");
      out.write("                        <h6>About Us</h6>\r\n");
      out.write("                        <h2>Welcome to <br>Roberto Hotel Luxury</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"about-us-content mb-100\">\r\n");
      out.write("                        <h5 class=\"wow fadeInUp\" data-wow-delay=\"300ms\">With over 340 hotels worldwide, NH Hotel Group offers a wide variety of hotels catering for a perfect stay no matter where your destination.</h5>\r\n");
      out.write("                        <p class=\"wow fadeInUp\" data-wow-delay=\"400ms\">Manager: <span>Michen Taylor</span></p>\r\n");
      out.write("                        <img src=\"img/core-img/signature.png\" alt=\"\" class=\"wow fadeInUp\" data-wow-delay=\"500ms\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-6\">\r\n");
      out.write("                    <div class=\"about-us-thumbnail mb-100 wow fadeInUp\" data-wow-delay=\"700ms\">\r\n");
      out.write("                        <div class=\"row no-gutters\">\r\n");
      out.write("                            <div class=\"col-6\">\r\n");
      out.write("                                <div class=\"single-thumb\">\r\n");
      out.write("                                    <img src=\"img/bg-img/13.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"single-thumb\">\r\n");
      out.write("                                    <img src=\"img/bg-img/14.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-6\">\r\n");
      out.write("                                <div class=\"single-thumb\">\r\n");
      out.write("                                    <img src=\"img/bg-img/15.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- About Us Area End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Service Area Start -->\r\n");
      out.write("    <div class=\"roberto-service-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"service-content d-flex align-items-center justify-content-between\">\r\n");
      out.write("                        <!-- Single Service Area -->\r\n");
      out.write("                        <div class=\"single-service--area mb-100 wow fadeInUp\" data-wow-delay=\"100ms\">\r\n");
      out.write("                            <img src=\"img/core-img/icon-1.png\" alt=\"\">\r\n");
      out.write("                            <h5>Transportion</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Single Service Area -->\r\n");
      out.write("                        <div class=\"single-service--area mb-100 wow fadeInUp\" data-wow-delay=\"300ms\">\r\n");
      out.write("                            <img src=\"img/core-img/icon-2.png\" alt=\"\">\r\n");
      out.write("                            <h5>Reiseservice</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Single Service Area -->\r\n");
      out.write("                        <div class=\"single-service--area mb-100 wow fadeInUp\" data-wow-delay=\"500ms\">\r\n");
      out.write("                            <img src=\"img/core-img/icon-3.png\" alt=\"\">\r\n");
      out.write("                            <h5>Spa Relaxtion</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Single Service Area -->\r\n");
      out.write("                        <div class=\"single-service--area mb-100 wow fadeInUp\" data-wow-delay=\"700ms\">\r\n");
      out.write("                            <img src=\"img/core-img/icon-4.png\" alt=\"\">\r\n");
      out.write("                            <h5>Restaurant</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Single Service Area -->\r\n");
      out.write("                        <div class=\"single-service--area mb-100 wow fadeInUp\" data-wow-delay=\"900ms\">\r\n");
      out.write("                            <img src=\"img/core-img/icon-1.png\" alt=\"\">\r\n");
      out.write("                            <h5>Bar &amp; Drink</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Service Area End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Our Room Area Start -->\r\n");
      out.write("    <section class=\"roberto-rooms-area\">\r\n");
      out.write("        <div class=\"rooms-slides owl-carousel\">\r\n");
      out.write("            <!-- Single Room Slide -->\r\n");
      out.write("            <div class=\"single-room-slide d-flex align-items-center\">\r\n");
      out.write("                <!-- Thumbnail -->\r\n");
      out.write("                <div class=\"room-thumbnail h-100 bg-img\" style=\"background-image: url(img/bg-img/16.jpg);\"></div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Content -->\r\n");
      out.write("                <div class=\"room-content\">\r\n");
      out.write("                    <h2 data-animation=\"fadeInUp\" data-delay=\"100ms\">Premium King Room</h2>\r\n");
      out.write("                    <h3 data-animation=\"fadeInUp\" data-delay=\"300ms\">400$ <span>/ Day</span></h3>\r\n");
      out.write("                    <ul class=\"room-feature\" data-animation=\"fadeInUp\" data-delay=\"500ms\">\r\n");
      out.write("                        <li><span><i class=\"fa fa-check\"></i> Size</span> <span>: 30 ft</span></li>\r\n");
      out.write("                        <li><span><i class=\"fa fa-check\"></i> Capacity</span> <span>: Max persion 5</span></li>\r\n");
      out.write("                        <li><span><i class=\"fa fa-check\"></i> Bed</span> <span>: King Beds</span></li>\r\n");
      out.write("                        <li><span><i class=\"fa fa-check\"></i> Services</span> <span>: Wifi, Television, Bathroom</span></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <a href=\"#\" class=\"btn roberto-btn mt-30\" data-animation=\"fadeInUp\" data-delay=\"700ms\">View Details</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Single Room Slide -->\r\n");
      out.write("            <div class=\"single-room-slide d-flex align-items-center\">\r\n");
      out.write("                <!-- Thumbnail -->\r\n");
      out.write("                <div class=\"room-thumbnail h-100 bg-img\" style=\"background-image: url(img/bg-img/17.jpg);\"></div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Content -->\r\n");
      out.write("                <div class=\"room-content\">\r\n");
      out.write("                    <h2 data-animation=\"fadeInUp\" data-delay=\"100ms\">Best King Room</h2>\r\n");
      out.write("                    <h3 data-animation=\"fadeInUp\" data-delay=\"300ms\">125$ <span>/ Day</span></h3>\r\n");
      out.write("                    <ul class=\"room-feature\" data-animation=\"fadeInUp\" data-delay=\"500ms\">\r\n");
      out.write("                        <li><span><i class=\"fa fa-check\"></i> Size</span> <span>: 30 ft</span></li>\r\n");
      out.write("                        <li><span><i class=\"fa fa-check\"></i> Capacity</span> <span>: Max persion 5</span></li>\r\n");
      out.write("                        <li><span><i class=\"fa fa-check\"></i> Bed</span> <span>: King Beds</span></li>\r\n");
      out.write("                        <li><span><i class=\"fa fa-check\"></i> Services</span> <span>: Wifi, Television, Bathroom</span></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <a href=\"#\" class=\"btn roberto-btn mt-30\" data-animation=\"fadeInUp\" data-delay=\"700ms\">View Details</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Our Room Area End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Testimonials Area Start -->\r\n");
      out.write("    <section class=\"roberto-testimonials-area section-padding-100-0\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center\">\r\n");
      out.write("                <div class=\"col-12 col-md-6\">\r\n");
      out.write("                    <div class=\"testimonial-thumbnail owl-carousel mb-100\">\r\n");
      out.write("                        <img src=\"img/bg-img/10.jpg\" alt=\"\">\r\n");
      out.write("                        <img src=\"img/bg-img/11.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-md-6\">\r\n");
      out.write("                    <!-- Section Heading -->\r\n");
      out.write("                    <div class=\"section-heading\">\r\n");
      out.write("                        <h6>Testimonials</h6>\r\n");
      out.write("                        <h2>Our Guests Love Us</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Testimonial Slide -->\r\n");
      out.write("                    <div class=\"testimonial-slides owl-carousel mb-100\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Single Testimonial Slide -->\r\n");
      out.write("                        <div class=\"single-testimonial-slide\">\r\n");
      out.write("                            <h5>âThis can be achieved by applying search engine optimization or popularly known as SEO. This is a marketing strategy which increases the quality and quantity of traffic flow to a particular website via search engines.â</h5>\r\n");
      out.write("                            <div class=\"rating-title\">\r\n");
      out.write("                                <div class=\"rating\">\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <h6>Robert Downey <span>- CEO Deercreative</span></h6>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Single Testimonial Slide -->\r\n");
      out.write("                        <div class=\"single-testimonial-slide\">\r\n");
      out.write("                            <h5>âLorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus delectus facilis molestias, error vitae praesentium quos eaque qui ea, tempore blanditiis sint reprehenderit, quaerat. Commodi ab architecto sit suscipit exercitationem!â</h5>\r\n");
      out.write("                            <div class=\"rating-title\">\r\n");
      out.write("                                <div class=\"rating\">\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <h6>Akash Downey <span>- CEO Deercreative</span></h6>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Single Testimonial Slide -->\r\n");
      out.write("                        <div class=\"single-testimonial-slide\">\r\n");
      out.write("                            <h5>âLorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor, ex quos. Alias a rem maiores, possimus dicta sit distinctio quis iusto!â</h5>\r\n");
      out.write("                            <div class=\"rating-title\">\r\n");
      out.write("                                <div class=\"rating\">\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <h6>Downey Sarah <span>- CEO Deercreative</span></h6>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Single Testimonial Slide -->\r\n");
      out.write("                        <div class=\"single-testimonial-slide\">\r\n");
      out.write("                            <h5>âLorem ipsum dolor sit amet, consectetur adipisicing elit. Labore sequi laboriosam fugit suscipit aspernatur, minima minus voluptatum, id ab atque similique ex earum. Magni.â</h5>\r\n");
      out.write("                            <div class=\"rating-title\">\r\n");
      out.write("                                <div class=\"rating\">\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                    <i class=\"icon_star\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <h6>Robert Brown <span>- CEO Deercreative</span></h6>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Testimonials Area End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Projects Area Start -->\r\n");
      out.write("    <section class=\"roberto-project-area\">\r\n");
      out.write("        <!-- Projects Slide -->\r\n");
      out.write("        <div class=\"projects-slides owl-carousel\">\r\n");
      out.write("            <!-- Single Project Slide -->\r\n");
      out.write("            <div class=\"single-project-slide active bg-img\" style=\"background-image: url(img/bg-img/5.jpg);\">\r\n");
      out.write("                <!-- Project Text -->\r\n");
      out.write("                <div class=\"project-content\">\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h6>Entertaiment</h6>\r\n");
      out.write("                        <h5>Racing Bike</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Hover Effects -->\r\n");
      out.write("                <div class=\"hover-effects\">\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h6>Entertaiment</h6>\r\n");
      out.write("                        <h5>Racing Bike</h5>\r\n");
      out.write("                        <p>I focus a lot on helping the first time or inexperienced traveler head out prepared and confident...</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn project-btn\">Discover Now <i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Single Project Slide -->\r\n");
      out.write("            <div class=\"single-project-slide bg-img\" style=\"background-image: url(img/bg-img/6.jpg);\">\r\n");
      out.write("                <!-- Project Text -->\r\n");
      out.write("                <div class=\"project-content\">\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h6>Entertaiment</h6>\r\n");
      out.write("                        <h5>Racing Bike</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Hover Effects -->\r\n");
      out.write("                <div class=\"hover-effects\">\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h6>Entertaiment</h6>\r\n");
      out.write("                        <h5>Racing Bike</h5>\r\n");
      out.write("                        <p>I focus a lot on helping the first time or inexperienced traveler head out prepared and confident...</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn project-btn\">Discover Now <i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Single Project Slide -->\r\n");
      out.write("            <div class=\"single-project-slide bg-img\" style=\"background-image: url(img/bg-img/7.jpg);\">\r\n");
      out.write("                <!-- Project Text -->\r\n");
      out.write("                <div class=\"project-content\">\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h6>Entertaiment</h6>\r\n");
      out.write("                        <h5>Racing Bike</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Hover Effects -->\r\n");
      out.write("                <div class=\"hover-effects\">\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h6>Entertaiment</h6>\r\n");
      out.write("                        <h5>Racing Bike</h5>\r\n");
      out.write("                        <p>I focus a lot on helping the first time or inexperienced traveler head out prepared and confident...</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn project-btn\">Discover Now <i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Single Project Slide -->\r\n");
      out.write("            <div class=\"single-project-slide bg-img\" style=\"background-image: url(img/bg-img/8.jpg);\">\r\n");
      out.write("                <!-- Project Text -->\r\n");
      out.write("                <div class=\"project-content\">\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h6>Entertaiment</h6>\r\n");
      out.write("                        <h5>Racing Bike</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Hover Effects -->\r\n");
      out.write("                <div class=\"hover-effects\">\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h6>Entertaiment</h6>\r\n");
      out.write("                        <h5>Racing Bike</h5>\r\n");
      out.write("                        <p>I focus a lot on helping the first time or inexperienced traveler head out prepared and confident...</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn project-btn\">Discover Now <i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Single Project Slide -->\r\n");
      out.write("            <div class=\"single-project-slide bg-img\" style=\"background-image: url(img/bg-img/9.jpg);\">\r\n");
      out.write("                <!-- Project Text -->\r\n");
      out.write("                <div class=\"project-content\">\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h6>Entertaiment</h6>\r\n");
      out.write("                        <h5>Racing Bike</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Hover Effects -->\r\n");
      out.write("                <div class=\"hover-effects\">\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h6>Entertaiment</h6>\r\n");
      out.write("                        <h5>Racing Bike</h5>\r\n");
      out.write("                        <p>I focus a lot on helping the first time or inexperienced traveler head out prepared and confident...</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn project-btn\">Discover Now <i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Projects Area End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Blog Area Start -->\r\n");
      out.write("    <section class=\"roberto-blog-area section-padding-100-0\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <!-- Section Heading -->\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"section-heading text-center wow fadeInUp\" data-wow-delay=\"100ms\">\r\n");
      out.write("                        <h6>Our Blog</h6>\r\n");
      out.write("                        <h2>Latest News &amp; Event</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <!-- Single Post Area -->\r\n");
      out.write("                <div class=\"col-12 col-md-6 col-lg-4\">\r\n");
      out.write("                    <div class=\"single-post-area mb-100 wow fadeInUp\" data-wow-delay=\"300ms\">\r\n");
      out.write("                        <a href=\"#\" class=\"post-thumbnail\"><img src=\"img/bg-img/2.jpg\" alt=\"\"></a>\r\n");
      out.write("                        <!-- Post Meta -->\r\n");
      out.write("                        <div class=\"post-meta\">\r\n");
      out.write("                            <a href=\"#\" class=\"post-date\">Jan 02, 2019</a>\r\n");
      out.write("                            <a href=\"#\" class=\"post-catagory\">Event</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Post Title -->\r\n");
      out.write("                        <a href=\"#\" class=\"post-title\">Learn How To Motivate Yourself</a>\r\n");
      out.write("                        <p>How many free autoresponders have you tried? And how many emails did you get through using them?</p>\r\n");
      out.write("                        <a href=\"index.html\" class=\"btn continue-btn\"><i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Single Post Area -->\r\n");
      out.write("                <div class=\"col-12 col-md-6 col-lg-4\">\r\n");
      out.write("                    <div class=\"single-post-area mb-100 wow fadeInUp\" data-wow-delay=\"500ms\">\r\n");
      out.write("                        <a href=\"#\" class=\"post-thumbnail\"><img src=\"img/bg-img/3.jpg\" alt=\"\"></a>\r\n");
      out.write("                        <!-- Post Meta -->\r\n");
      out.write("                        <div class=\"post-meta\">\r\n");
      out.write("                            <a href=\"#\" class=\"post-date\">Jan 02, 2019</a>\r\n");
      out.write("                            <a href=\"#\" class=\"post-catagory\">Event</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Post Title -->\r\n");
      out.write("                        <a href=\"#\" class=\"post-title\">What If Let You Run The Hubble</a>\r\n");
      out.write("                        <p>My point here is that if you have no clue for the answers above you probably are not operating a followup.</p>\r\n");
      out.write("                        <a href=\"index.html\" class=\"btn continue-btn\"><i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Single Post Area -->\r\n");
      out.write("                <div class=\"col-12 col-md-6 col-lg-4\">\r\n");
      out.write("                    <div class=\"single-post-area mb-100 wow fadeInUp\" data-wow-delay=\"700ms\">\r\n");
      out.write("                        <a href=\"#\" class=\"post-thumbnail\"><img src=\"img/bg-img/4.jpg\" alt=\"\"></a>\r\n");
      out.write("                        <!-- Post Meta -->\r\n");
      out.write("                        <div class=\"post-meta\">\r\n");
      out.write("                            <a href=\"#\" class=\"post-date\">Jan 02, 2019</a>\r\n");
      out.write("                            <a href=\"#\" class=\"post-catagory\">Event</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Post Title -->\r\n");
      out.write("                        <a href=\"#\" class=\"post-title\">Six Pack Abs The Big Picture</a>\r\n");
      out.write("                        <p>Some good steps to take to ensure you are getting what you need out of a autoresponder includeâ¦</p>\r\n");
      out.write("                        <a href=\"index.html\" class=\"btn continue-btn\"><i class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Blog Area End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Call To Action Area Start -->\r\n");
      out.write("    <section class=\"roberto-cta-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"cta-content bg-img bg-overlay jarallax\" style=\"background-image: url(img/bg-img/1.jpg);\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-12 col-md-7\">\r\n");
      out.write("                        <div class=\"cta-text mb-50\">\r\n");
      out.write("                            <h2>Contact us now!</h2>\r\n");
      out.write("                            <h6>Contact (+12) 345-678-9999 to book directly or for advice</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12 col-md-5 text-right\">\r\n");
      out.write("                        <a href=\"#\" class=\"btn roberto-btn mb-50\">Contact Now</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Call To Action Area End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Partner Area Start -->\r\n");
      out.write("    <div class=\"partner-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"partner-logo-content d-flex align-items-center justify-content-between wow fadeInUp\" data-wow-delay=\"300ms\">\r\n");
      out.write("                        <!-- Single Partner Logo -->\r\n");
      out.write("                        <a href=\"#\" class=\"partner-logo\"><img src=\"img/core-img/p1.png\" alt=\"\"></a>\r\n");
      out.write("                        <!-- Single Partner Logo -->\r\n");
      out.write("                        <a href=\"#\" class=\"partner-logo\"><img src=\"img/core-img/p2.png\" alt=\"\"></a>\r\n");
      out.write("                        <!-- Single Partner Logo -->\r\n");
      out.write("                        <a href=\"#\" class=\"partner-logo\"><img src=\"img/core-img/p3.png\" alt=\"\"></a>\r\n");
      out.write("                        <!-- Single Partner Logo -->\r\n");
      out.write("                        <a href=\"#\" class=\"partner-logo\"><img src=\"img/core-img/p4.png\" alt=\"\"></a>\r\n");
      out.write("                        <!-- Single Partner Logo -->\r\n");
      out.write("                        <a href=\"#\" class=\"partner-logo\"><img src=\"img/core-img/p5.png\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Partner Area End -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write(' ');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
