/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2022-01-16 17:54:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("     \r\n");
      out.write("        <!-- Masthead-->\r\n");
      out.write("        <header class=\"masthead\">\r\n");
      out.write("            <div class=\"container position-relative\">\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                    <div class=\"col-xl-6\">\r\n");
      out.write("                        <div class=\"text-center text-white\">\r\n");
      out.write("                            <!-- Page heading-->\r\n");
      out.write("                            <h1 class=\"mb-5\">Generate more leads with a professional landing page!</h1>\r\n");
      out.write("                            <!-- Signup form-->\r\n");
      out.write("                            <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                            <!-- * * SB Forms Contact Form * *-->\r\n");
      out.write("                            <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                            <!-- This form is pre-integrated with SB Forms.-->\r\n");
      out.write("                            <!-- To make this form functional, sign up at-->\r\n");
      out.write("                            <!-- https://startbootstrap.com/solution/contact-forms-->\r\n");
      out.write("                            <!-- to get an API token!-->\r\n");
      out.write("                            <form class=\"form-subscribe\" id=\"contactForm\" data-sb-form-api-token=\"API_TOKEN\">\r\n");
      out.write("                                <!-- Email address input-->\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col\">\r\n");
      out.write("                                        <input class=\"form-control form-control-lg\" id=\"emailAddress\" type=\"email\" placeholder=\"Email Address\" data-sb-validations=\"required,email\" />\r\n");
      out.write("                                        <div class=\"invalid-feedback text-white\" data-sb-feedback=\"emailAddress:required\">Email Address is required.</div>\r\n");
      out.write("                                        <div class=\"invalid-feedback text-white\" data-sb-feedback=\"emailAddress:email\">Email Address Email is not valid.</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-auto\"><button class=\"btn btn-primary btn-lg disabled\" id=\"submitButton\" type=\"button\">Submit</button></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Submit success message-->\r\n");
      out.write("                                <!---->\r\n");
      out.write("                                <!-- This is what your users will see when the form-->\r\n");
      out.write("                                <!-- has successfully submitted-->\r\n");
      out.write("                                <div class=\"d-none\" id=\"submitSuccessMessage\">\r\n");
      out.write("                                    <div class=\"text-center mb-3\">\r\n");
      out.write("                                        <div class=\"fw-bolder\">Form submission successful!</div>\r\n");
      out.write("                                        <p>To activate this form, sign up at</p>\r\n");
      out.write("                                        <a class=\"text-white\" href=\"https://startbootstrap.com/solution/contact-forms\">https://startbootstrap.com/solution/contact-forms</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Submit error message-->\r\n");
      out.write("                                <!---->\r\n");
      out.write("                                <!-- This is what your users will see when there is-->\r\n");
      out.write("                                <!-- an error submitting the form-->\r\n");
      out.write("                                <div class=\"d-none\" id=\"submitErrorMessage\"><div class=\"text-center text-danger mb-3\">Error sending message!</div></div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- Image Showcases-->\r\n");
      out.write("        <section class=\"showcase\">\r\n");
      out.write("            <div class=\"container-fluid p-0\">\r\n");
      out.write("                <div class=\"row g-0\">\r\n");
      out.write("                    <div class=\"col-lg-6 order-lg-2 text-white showcase-img\" style=\"background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/img/bg-showcase-1.jpg')\"></div>\r\n");
      out.write("                    <div class=\"col-lg-6 order-lg-1 my-auto showcase-text\">\r\n");
      out.write("                        <h2>Fully Responsive Design</h2>\r\n");
      out.write("                        <p class=\"lead mb-0\">When you use a theme created by Start Bootstrap, you know that the theme will look great on any device, whether it's a phone, tablet, or desktop the page will behave responsively!</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row g-0\">\r\n");
      out.write("                    <div class=\"col-lg-6 text-white showcase-img\" style=\"background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/img/bg-showcase-2.jpg')\"></div>\r\n");
      out.write("                    <div class=\"col-lg-6 my-auto showcase-text\">\r\n");
      out.write("                        <h2>Updated For Bootstrap 5</h2>\r\n");
      out.write("                        <p class=\"lead mb-0\">Newly improved, and full of great utility classes, Bootstrap 5 is leading the way in mobile responsive web development! All of the themes on Start Bootstrap are now using Bootstrap 5!</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row g-0\">\r\n");
      out.write("                    <div class=\"col-lg-6 order-lg-2 text-white showcase-img\" style=\"background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/img/bg-showcase-3.jpg')\"></div>\r\n");
      out.write("                    <div class=\"col-lg-6 order-lg-1 my-auto showcase-text\">\r\n");
      out.write("                        <h2>Easy to Use & Customize</h2>\r\n");
      out.write("                        <p class=\"lead mb-0\">Landing Page is just HTML and CSS with a splash of SCSS for users who demand some deeper customization options. Out of the box, just add your content and images, and your new landing page will be ready to go!</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Testimonials-->\r\n");
      out.write("        <section class=\"testimonials text-center bg-light\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <h2 class=\"mb-5\">What people are saying...</h2>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <div class=\"testimonial-item mx-auto mb-5 mb-lg-0\">\r\n");
      out.write("                            <img class=\"img-fluid rounded-circle mb-3\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/img/testimonials-1.jpg\" alt=\"...\" />\r\n");
      out.write("                            <h5>Margaret E.</h5>\r\n");
      out.write("                            <p class=\"font-weight-light mb-0\">\"This is fantastic! Thanks so much guys!\"</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <div class=\"testimonial-item mx-auto mb-5 mb-lg-0\">\r\n");
      out.write("                            <img class=\"img-fluid rounded-circle mb-3\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/img/testimonials-2.jpg\" alt=\"...\" />\r\n");
      out.write("                            <h5>Fred S.</h5>\r\n");
      out.write("                            <p class=\"font-weight-light mb-0\">\"Bootstrap is amazing. I've been using it to create lots of super nice landing pages.\"</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <div class=\"testimonial-item mx-auto mb-5 mb-lg-0\">\r\n");
      out.write("                            <img class=\"img-fluid rounded-circle mb-3\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/img/testimonials-3.jpg\" alt=\"...\" />\r\n");
      out.write("                            <h5>Sarah W.</h5>\r\n");
      out.write("                            <p class=\"font-weight-light mb-0\">\"Thanks so much for making these free resources available to us!\"</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Call to Action-->\r\n");
      out.write("        <section class=\"call-to-action text-white text-center\" id=\"signup\">\r\n");
      out.write("            <div class=\"container position-relative\">\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                    <div class=\"col-xl-6\">\r\n");
      out.write("                        <h2 class=\"mb-4\">Ready to get started? Sign up now!</h2>\r\n");
      out.write("                        <!-- Signup form-->\r\n");
      out.write("                        <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                        <!-- * * SB Forms Contact Form * *-->\r\n");
      out.write("                        <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                        <!-- This form is pre-integrated with SB Forms.-->\r\n");
      out.write("                        <!-- To make this form functional, sign up at-->\r\n");
      out.write("                        <!-- https://startbootstrap.com/solution/contact-forms-->\r\n");
      out.write("                        <!-- to get an API token!-->\r\n");
      out.write("                        <form class=\"form-subscribe\" id=\"contactFormFooter\" data-sb-form-api-token=\"API_TOKEN\">\r\n");
      out.write("                            <!-- Email address input-->\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col\">\r\n");
      out.write("                                    <input class=\"form-control form-control-lg\" id=\"emailAddressBelow\" type=\"email\" placeholder=\"Email Address\" data-sb-validations=\"required,email\" />\r\n");
      out.write("                                    <div class=\"invalid-feedback text-white\" data-sb-feedback=\"emailAddressBelow:required\">Email Address is required.</div>\r\n");
      out.write("                                    <div class=\"invalid-feedback text-white\" data-sb-feedback=\"emailAddressBelow:email\">Email Address Email is not valid.</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-auto\"><button class=\"btn btn-primary btn-lg disabled\" id=\"submitButton\" type=\"button\">Submit</button></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Submit success message-->\r\n");
      out.write("                            <!---->\r\n");
      out.write("                            <!-- This is what your users will see when the form-->\r\n");
      out.write("                            <!-- has successfully submitted-->\r\n");
      out.write("                            <div class=\"d-none\" id=\"submitSuccessMessage\">\r\n");
      out.write("                                <div class=\"text-center mb-3\">\r\n");
      out.write("                                    <div class=\"fw-bolder\">Form submission successful!</div>\r\n");
      out.write("                                    <p>To activate this form, sign up at</p>\r\n");
      out.write("                                    <a class=\"text-white\" href=\"https://startbootstrap.com/solution/contact-forms\">https://startbootstrap.com/solution/contact-forms</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Submit error message-->\r\n");
      out.write("                            <!---->\r\n");
      out.write("                            <!-- This is what your users will see when there is-->\r\n");
      out.write("                            <!-- an error submitting the form-->\r\n");
      out.write("                            <div class=\"d-none\" id=\"submitErrorMessage\"><div class=\"text-center text-danger mb-3\">Error sending message!</div></div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("    \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
